services:
  - type: web
    name: vinvalue
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
      - key: WEBUYEMAIL
        sync: false
      - key: WEBUYZIPCODE
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    # No persistent disk needed when PLAYWRIGHT_BROWSERS_PATH=0 (browsers ship in node_modules)

